# Generated by Django 3.1 on 2021-09-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210717_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
