# Generated by Django 3.1 on 2021-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210911_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gif_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
