# Generated by Django 3.1 on 2021-09-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_blog_gif_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='image',
        ),
    ]
