# Generated by Django 3.1 on 2021-09-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_gif_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='gif_link',
        ),
    ]
