# Generated by Django 3.1 on 2021-09-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210914_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
