# Generated by Django 3.1 on 2021-09-26 04:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('advert', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('home', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=False)),
                ('store', models.BooleanField(default=False)),
                ('audio', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('account', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='app/videos/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('news', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('news_detail', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('audio', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('video', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('store', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('choice', models.CharField(choices=[('Tattoo', 'Tattoo'), ('Haircut', 'Haircut'), ('Event', 'Event'), ('Others', 'Others')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nextmatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(blank=True, max_length=20)),
                ('host', models.CharField(blank=True, max_length=30)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='app/images/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('donate', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('what_we_do', models.TextField(blank=True, null=True)),
                ('our_mission', models.TextField(blank=True, null=True)),
                ('our_vision', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('privacypolicy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tandc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.videocategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='app/videos/')),
                ('podcast', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.videocategory')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='app/images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.portfolio')),
            ],
        ),
    ]
