# Generated by Django 3.1 on 2021-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('news_detail', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('audio', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('video', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
                ('store', models.ImageField(blank=True, upload_to='images/breadcrumb/')),
            ],
        ),
    ]
