# Generated by Django 3.1 on 2021-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_breadcrumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nextmatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
