# Generated by Django 3.1 on 2021-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_setting_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
