# Generated by Django 3.1 on 2021-07-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advert',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='breadcrumb',
            name='home',
            field=models.ImageField(blank=True, upload_to='images/breadcrumb/'),
        ),
    ]
